// 09_MongoDB_MongoDB_Collection_Modell_Schema
const mongoose = require("mongoose");
const mongooseSchema = mongoose.Schema;
const schema = new mongooseSchema(
  {
    _title: {
      type: String,
      required: true,
    },
    _year: {
      type: Number,
      required: true,
    },
    _description: {
      type: String,
      required: true,
    },
  },
  // autogenerated fields: createdAt and updatedAt
  { timestamps: false },
);

// 09_MongoDB_Collection_Modell
const Movies = mongoose.model("tb_movies", schema);
module.exports = Movies;
