const { Sequelize, DataTypes } = require("sequelize");

/* Configuration - Option 1 */
/* one of 'mysql' | 'postgres' | 'sqlite' | 'mariadb' | 'mssql' | 'db2' | 'snowflake' | 'oracle' */
const sequelize = new Sequelize("db_mysql", "user", "Passw!0rd123", {
  host: "localhost",
  dialect: "mysql",
});

const Movies = sequelize.define(
  "Movies",
  {
    _id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    _title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    _year: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    _description: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  },
  {
    // autogenerated fields: createdAt and updatedAt
    timestamps: false,
    // database table
    tableName: "tb_movies",
  },
);

module.exports = Movies;
