---
- hosts: ubuntu
  gather_facts: yes
  become: yes

  tasks:
    - name: TASK-1 - Install latest Apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: TASK-2 - Enable mod_rewrite
      apache2_module:
        name: rewrite
        state: present

    - name: TASK-3 - Restart Apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
