---
- hosts: ubuntu
  gather_facts: yes
  become: yes

  tasks:
    - name: TASK-1 - Install latest MariaDB
      ansible.builtin.apt:
        name: mariadb-server
        update_cache: yes
        state: latest

    - name: TASK-2 - Start and enable MariaDB
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: TASK-3 - Secure MariaDB
      mysql_secure_installation:
        login_password: ""
        root_password: "PASSWORD"
        remove_anonymous_users: yes
        disallow_root_login_remotely: yes
        remove_test_database: yes
        create_db_user: yes
        db_user_name: DB_USER
        db_user_password: DB_PASSWORD
        create_database: yes
        database: DB_NAME
        state: present
