# !/bin/bash
# BEFORE RUN docker compose up -d
# sudo echo "vm.max_map_count=262144" >> /etc/sysctl.conf
# sudo sysctl -p

services:
  # MongoDB https://hub.docker.com/_/mongo/
  mongodb:
    image: "mongo:7.0"
    container_name: "mongodb"
    hostname: "mongodb"
    restart: "unless-stopped"
    volumes:
      - "./data/mongodb/db:/data/db"
      - "./data/mongodb/configdb:/data/configdb"
    environment:
      - "TZ=Europe/Berlin"

  # DATANODE https://hub.docker.com/r/graylog/graylog-datanode
  datanode:
    image: "graylog/graylog-datanode:7.0"
    container_name: "datanode"
    hostname: "datanode"
    restart: "unless-stopped"
    ports:
      - "8999:8999"
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./data/datanode:/var/lib/graylog-datanode"
    environment:
      - "GRAYLOG_TIMEZONE=Europe/Berlin"
      - "GRAYLOG_DATANODE_NODE_ID_FILE=/var/lib/graylog-datanode/node-id"
      - "GRAYLOG_DATANODE_MONGODB_URI=mongodb://mongodb:27017/graylog"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      # !/bin/bash
      # < /dev/urandom tr -dc A-Z-a-z-0-9 | head -c${1:-96};echo;
      - "GRAYLOG_DATANODE_PASSWORD_SECRET=YOURsecretPEPPER"
    ulimits:
      memlock:
        hard: "-1"
        soft: "-1"
      nofile:
        soft: "65536"
        hard: "65536"
    depends_on:
      mongodb:
        condition: "service_started"

  # GRAYLOG https://hub.docker.com/r/graylog/graylog/
  # sudo mkdir ./data/graylog/data
  # sudo chown -R 1100:1100 ./data/graylog/data
  # AFTER RUN docker compose up -d
  # docker logs [GRAYLOG-ID] for FIRST INSTALL ADMIN-PW
  graylog:
    image: "graylog/graylog:7.0"
    container_name: "graylog"
    hostname: "graylog"
    restart: "unless-stopped"
    ports:
      # Graylog webui
      - "9000:9000"
      # Beats
      - "5044:5044/tcp"
      # Syslog TCP
      - "5140:5140/tcp"
      # Syslog UDP
      - "5140:5140/udp"
      # GELF TCP
      - "12201:12201/tcp"
      # GELF UDP
      - "12201:12201/udp"
      # Forwarder data
      - "13301:13301/tcp"
      # Forwarder config
      - "13302:13302/tcp"
    volumes:
      - "./data/graylog/data:/usr/share/graylog/data/data"
    environment:
      - "GRAYLOG_TIMEZONE=Europe/Berlin"
      - "GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/data/node-id"
      - "GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000"
      - "GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/"
      - "GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      - "GRAYLOG_PASSWORD_SECRET=YOURsecretPEPPER"
      # !/bin/bash
      # echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
      # Password: 1234567890
      - "GRAYLOG_ROOT_PASSWORD_SHA2=c775e7b757ede630cd0aa1113bd102661ab38829ca52a6422ab782862f268646"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    depends_on:
      mongodb:
        condition: "service_started"
      datanode:
        condition: "service_started"

  filebeat:
    image: "elastic/filebeat:9.1.7"
    container_name: "filebeat"
    hostname: "filebeat"
    restart: "unless-stopped"
    volumes:
      - "./data/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - "./data./filebeat/logs:/usr/share/filebeat/dockerlogs"

networks:
  default:
    name: "graylog_network"