services:
  uptime-kuma:
    image: "louislam/uptime-kuma:latest"
    container_name: "uptime-kuma"
    hostname: "uptime-kuma"
    restart: "unless-stopped"
    ports:
      - "3001:3001"
    volumes:
      - "./data:/app/data"
    environment:
      - "TZ=Europe/Berlin"
      - "UMASK=0022"

networks:
  default:
    name: "uptime-kuma_network"